export const inventoryData = [
  {
    "id": "veh_001",
    "vin": "1HGCM82633A123456",
    "stockNumber": "STK-10234",
    "status": "available",
    "type": "used",
    "vehicleInfo": {
      "year": 2021,
      "make": "Toyota",
      "model": "Camry",
      "trim": "SE",
      "bodyStyle": "Sedan",
      "drivetrain": "FWD",
      "engine": "2.5L I4",
      "transmission": "Automatic",
      "fuelType": "Gasoline",
      "mpg": { "city": 28, "highway": 39 },
      "exteriorColor": "Black",
      "interiorColor": "Black",
      "doors": 4
    },
    "pricing": {
      "listPrice": 23995,
      "salePrice": 22995,
      "cost": 20000,
      "msrp": 26000,
      "priceHistory": []
    },
    "mileage": 34210,
    "condition": "excellent",
    "features": ["Bluetooth", "Backup Camera", "Lane Assist"],
    "packages": ["Convenience Package"],
    "history": {
      "carfaxAvailable": true,
      "accidentsReported": 0,
      "previousOwners": 1,
      "serviceRecords": true
    },
    "media": { "thumbnail": "https://tmna.aemassets.toyota.com/is/image/toyota/toyota/jellies/max/2026/camry/nightshade/2558/3u5/36/5.png?fmt=png-alpha&wid=930&hei=328&qlt=90", "images": [], "videoUrl": "" },
    "location": { "dealershipId": "dealer_001", "lot": "Main Lot", "city": "Orlando", "state": "FL" },
    "dates": { "dateAdded": "2026-03-01T10:00:00Z", "lastUpdated": "2026-03-20T15:30:00Z" },
    "sales": { "daysOnLot": 22, "views": 134, "inquiries": 12, "testDrives": 4 },
    "flags": { "certifiedPreOwned": false, "featured": true, "priceReduced": true }
  },
  {
    "id": "veh_002",
    "vin": "1FTFW1ET5EKF51234",
    "stockNumber": "STK-10235",
    "status": "available",
    "type": "used",
    "vehicleInfo": {
      "year": 2020,
      "make": "Ford",
      "model": "F-150",
      "trim": "XLT",
      "bodyStyle": "Truck",
      "drivetrain": "4WD",
      "engine": "3.5L V6 EcoBoost",
      "transmission": "Automatic",
      "fuelType": "Gasoline",
      "mpg": { "city": 18, "highway": 24 },
      "exteriorColor": "Blue",
      "interiorColor": "Gray",
      "doors": 4
    },
    "pricing": {
      "listPrice": 32995,
      "salePrice": 31995,
      "cost": 29000,
      "msrp": 40000,
      "priceHistory": []
    },
    "mileage": 50120,
    "condition": "good",
    "features": ["4x4", "Tow Package", "Backup Camera"],
    "packages": ["Off-Road Package"],
    "history": { "carfaxAvailable": true, "accidentsReported": 1, "previousOwners": 2, "serviceRecords": true },
    "media": { "thumbnail": "https://tmna.aemassets.toyota.com/is/image/toyota/toyota/jellies/max/2026/camry/nightshade/2558/3u5/36/5.png?fmt=png-alpha&wid=930&hei=328&qlt=90", "images": [], "videoUrl": "" },
    "location": { "dealershipId": "dealer_001", "lot": "Truck Lot", "city": "Orlando", "state": "FL" },
    "dates": { "dateAdded": "2026-02-20T10:00:00Z", "lastUpdated": "2026-03-18T15:30:00Z" },
    "sales": { "daysOnLot": 31, "views": 210, "inquiries": 18, "testDrives": 6 },
    "flags": { "certifiedPreOwned": false, "featured": false, "priceReduced": false }
  },
  {
    "id": "veh_003",
    "vin": "5YJ3E1EA7KF123456",
    "stockNumber": "STK-10236",
    "status": "available",
    "type": "used",
    "vehicleInfo": {
      "year": 2019,
      "make": "Tesla",
      "model": "Model 3",
      "trim": "Standard Range Plus",
      "bodyStyle": "Sedan",
      "drivetrain": "RWD",
      "engine": "Electric",
      "transmission": "Automatic",
      "fuelType": "Electric",
      "mpg": { "city": 138, "highway": 126 },
      "exteriorColor": "White",
      "interiorColor": "Black",
      "doors": 4
    },
    "pricing": {
      "listPrice": 28995,
      "salePrice": 27995,
      "cost": 25000,
      "msrp": 39999,
      "priceHistory": []
    },
    "mileage": 28100,
    "condition": "excellent",
    "features": ["Autopilot", "Navigation", "Heated Seats"],
    "packages": [],
    "history": { "carfaxAvailable": true, "accidentsReported": 0, "previousOwners": 1, "serviceRecords": true },
    "media": { "thumbnail": "https://tmna.aemassets.toyota.com/is/image/toyota/toyota/jellies/max/2026/camry/nightshade/2558/3u5/36/5.png?fmt=png-alpha&wid=930&hei=328&qlt=90", "images": [], "videoUrl": "" },
    "location": { "dealershipId": "dealer_001", "lot": "EV Section", "city": "Orlando", "state": "FL" },
    "dates": { "dateAdded": "2026-03-05T10:00:00Z", "lastUpdated": "2026-03-21T15:30:00Z" },
    "sales": { "daysOnLot": 16, "views": 320, "inquiries": 25, "testDrives": 8 },
    "flags": { "certifiedPreOwned": false, "featured": true, "priceReduced": true }
  },
  {
    "id": "veh_004",
    "vin": "1C4RJFBG8LC123456",
    "stockNumber": "STK-10237",
    "status": "available",
    "type": "used",
    "vehicleInfo": {
      "year": 2022,
      "make": "Jeep",
      "model": "Grand Cherokee",
      "trim": "Limited",
      "bodyStyle": "SUV",
      "drivetrain": "4WD",
      "engine": "3.6L V6",
      "transmission": "Automatic",
      "fuelType": "Gasoline",
      "mpg": { "city": 19, "highway": 26 },
      "exteriorColor": "Silver",
      "interiorColor": "Black",
      "doors": 4
    },
    "pricing": {
      "listPrice": 38995,
      "salePrice": 37995,
      "cost": 35000,
      "msrp": 45000,
      "priceHistory": []
    },
    "mileage": 15200,
    "condition": "excellent",
    "features": ["4x4", "Leather Seats", "Sunroof"],
    "packages": ["Luxury Package"],
    "history": { "carfaxAvailable": true, "accidentsReported": 0, "previousOwners": 1, "serviceRecords": true },
    "media": { "thumbnail": "https://tmna.aemassets.toyota.com/is/image/toyota/toyota/jellies/max/2026/camry/nightshade/2558/3u5/36/5.png?fmt=png-alpha&wid=930&hei=328&qlt=90", "images": [], "videoUrl": "" },
    "location": { "dealershipId": "dealer_001", "lot": "SUV Row", "city": "Orlando", "state": "FL" },
    "dates": { "dateAdded": "2026-03-10T10:00:00Z", "lastUpdated": "2026-03-22T15:30:00Z" },
    "sales": { "daysOnLot": 12, "views": 98, "inquiries": 7, "testDrives": 2 },
    "flags": { "certifiedPreOwned": true, "featured": false, "priceReduced": false }
  },
  {
    "id": "veh_005",
    "vin": "3VWCB7BU5KM123456",
    "stockNumber": "STK-10238",
    "status": "available",
    "type": "used",
    "vehicleInfo": {
      "year": 2018,
      "make": "Volkswagen",
      "model": "Jetta",
      "trim": "SEL",
      "bodyStyle": "Sedan",
      "drivetrain": "FWD",
      "engine": "1.4L Turbo",
      "transmission": "Automatic",
      "fuelType": "Gasoline",
      "mpg": { "city": 30, "highway": 40 },
      "exteriorColor": "Red",
      "interiorColor": "Beige",
      "doors": 4
    },
    "pricing": {
      "listPrice": 17995,
      "salePrice": 16995,
      "cost": 15000,
      "msrp": 24000,
      "priceHistory": []
    },
    "mileage": 62100,
    "condition": "good",
    "features": ["Sunroof", "Backup Camera", "Bluetooth"],
    "packages": [],
    "history": { "carfaxAvailable": true, "accidentsReported": 1, "previousOwners": 2, "serviceRecords": false },
    "media": { "thumbnail": "https://tmna.aemassets.toyota.com/is/image/toyota/toyota/jellies/max/2026/camry/nightshade/2558/3u5/36/5.png?fmt=png-alpha&wid=930&hei=328&qlt=90", "images": [], "videoUrl": "" },
    "location": { "dealershipId": "dealer_001", "lot": "Main Lot", "city": "Orlando", "state": "FL" },
    "dates": { "dateAdded": "2026-02-15T10:00:00Z", "lastUpdated": "2026-03-17T15:30:00Z" },
    "sales": { "daysOnLot": 38, "views": 75, "inquiries": 5, "testDrives": 1 },
    "flags": { "certifiedPreOwned": false, "featured": false, "priceReduced": true }
  },
  {
    "id": "veh_006",
    "vin": "1N4AL3AP5JC123456",
    "stockNumber": "STK-10239",
    "status": "sold",
    "type": "used",
    "vehicleInfo": {
      "year": 2019,
      "make": "Nissan",
      "model": "Altima",
      "trim": "SV",
      "bodyStyle": "Sedan",
      "drivetrain": "AWD",
      "engine": "2.5L I4",
      "transmission": "CVT",
      "fuelType": "Gasoline",
      "mpg": { "city": 26, "highway": 36 },
      "exteriorColor": "Gray",
      "interiorColor": "Black",
      "doors": 4
    },
    "pricing": {
      "listPrice": 19995,
      "salePrice": 18995,
      "cost": 17000,
      "msrp": 27000,
      "priceHistory": []
    },
    "mileage": 45500,
    "condition": "good",
    "features": ["AWD", "Remote Start", "Apple CarPlay"],
    "packages": [],
    "history": { "carfaxAvailable": true, "accidentsReported": 0, "previousOwners": 1, "serviceRecords": true },
    "media": { "thumbnail": "https://tmna.aemassets.toyota.com/is/image/toyota/toyota/jellies/max/2026/camry/nightshade/2558/3u5/36/5.png?fmt=png-alpha&wid=930&hei=328&qlt=90", "images": [], "videoUrl": "" },
    "location": { "dealershipId": "dealer_001", "lot": "Main Lot", "city": "Orlando", "state": "FL" },
    "dates": { "dateAdded": "2026-02-10T10:00:00Z", "lastUpdated": "2026-03-10T15:30:00Z" },
    "sales": { "daysOnLot": 28, "views": 150, "inquiries": 20, "testDrives": 10 },
    "flags": { "certifiedPreOwned": false, "featured": false, "priceReduced": false }
  },
  {
    "id": "veh_007",
    "vin": "WBA3A5C58CF123456",
    "stockNumber": "STK-10240",
    "status": "available",
    "type": "used",
    "vehicleInfo": {
      "year": 2021,
      "make": "BMW",
      "model": "3 Series",
      "trim": "330i",
      "bodyStyle": "Sedan",
      "drivetrain": "RWD",
      "engine": "2.0L Turbo",
      "transmission": "Automatic",
      "fuelType": "Gasoline",
      "mpg": { "city": 26, "highway": 36 },
      "exteriorColor": "White",
      "interiorColor": "Brown",
      "doors": 4
    },
    "pricing": {
      "listPrice": 35995,
      "salePrice": 34995,
      "cost": 32000,
      "msrp": 42000,
      "priceHistory": []
    },
    "mileage": 22000,
    "condition": "excellent",
    "features": ["Navigation", "Leather Seats", "Heated Steering Wheel"],
    "packages": ["M Sport Package"],
    "history": { "carfaxAvailable": true, "accidentsReported": 0, "previousOwners": 1, "serviceRecords": true },
    "media": { "thumbnail": "https://tmna.aemassets.toyota.com/is/image/toyota/toyota/jellies/max/2026/camry/nightshade/2558/3u5/36/5.png?fmt=png-alpha&wid=930&hei=328&qlt=90", "images": [], "videoUrl": "" },
    "location": { "dealershipId": "dealer_001", "lot": "Luxury Row", "city": "Orlando", "state": "FL" },
    "dates": { "dateAdded": "2026-03-12T10:00:00Z", "lastUpdated": "2026-03-22T15:30:00Z" },
    "sales": { "daysOnLot": 10, "views": 180, "inquiries": 15, "testDrives": 5 },
    "flags": { "certifiedPreOwned": true, "featured": true, "priceReduced": false }
  }
]